server:
  port: 9891
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/computerpartsmall
    password: 123456

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml